// Generated by CoffeeScript 1.7.1
(function() {
  define(['jquery', 'TweenMax', 'angular', 'angular-animate'], function($, TweenMax) {
    var app, valueToWidth;
    app = angular.module('graph.animations', ['ngAnimate']);
    app.animation('.toggle-prompt', function() {
      var animate;
      return animate = {
        leave: function(ele, done) {
          TweenMax.to(ele, 0.3, {
            autoAlpha: 0,
            ease: Power3.easeOut,
            onComplete: done
          });
          TweenMax.to(ele, 0.3, {
            autoAlpha: 0,
            ease: Power3.easeOut,
            delay: 1
          });
        },
        enter: function(ele, done) {
          TweenMax.fromTo(ele, .6, {
            autoAlpha: 0
          }, {
            autoAlpha: 1,
            delay: 1,
            onComplete: done
          });
        }
      };
    });
    app.animation('.toggle-graph', function() {
      var animate;
      return animate = {
        leave: function(ele, done) {
          TweenMax.to(ele, 0.3, {
            autoAlpha: 0,
            y: 40,
            ease: Power3.easeOut,
            onComplete: done
          });
        },
        enter: function(ele, done) {
          TweenMax.fromTo($(ele).find('.y-axis'), .6, {
            height: 0
          }, {
            height: '100%',
            ease: Power3.easeOut,
            onComplete: done
          });
          TweenMax.fromTo($(ele).find('.data-item p'), .3, {
            autoAlpha: 0
          }, {
            autoAlpha: 1
          });
          $(ele).find('.data-item').each(function(i) {
            var $key, $value, delay, time, width;
            time = .9;
            delay = i / 40;
            $key = $(this).find('.key');
            TweenMax.fromTo($key, time, {
              autoAlpha: 0,
              x: 100
            }, {
              autoAlpha: 1,
              x: 0,
              ease: Power3.easeInOut,
              delay: delay
            });
            $value = $(this).find('.value');
            width = valueToWidth($value.data('width'));
            return TweenMax.fromTo($value, time, {
              width: 0
            }, {
              width: width,
              autoAlpha: 1,
              ease: Power3.easeInOut,
              delay: delay
            });
          });
        }
      };
    });
    valueToWidth = function(value) {
      return value * 380 / 6000;
    };
    return app;
  });

}).call(this);


//# sourceMappingURL=animations.map
